### PR TITLE
Reorganize CI and add automatic Zenodo registration

### PR DESCRIPTION
**Pull request by pkgw**
Let's get this stuff formally published!

### CODE REVIEW

**Comment by pkgw** [comment]
@cjordan @d3v-null In preparation for a batch of new releases, I would like to set up to formally publish the Rubbl to Zenodo, so that it gets a DOI and an author list and can be cited in academic contexts. I'd like to invite you two to join the Rubbl author list.

If you'd like to join, please provide me with a full name, affiliation, and ORCID ID if available, to use in the author list. @cjordan I think your GitHub profile has all that info, but if you wouldn't mind confirming everything, that would be helpful.

I have some nice automation based on [Cranko] that will then do all of the Zenodo magic and even embed the DOIs in the CLI tool. The authorship information will be recorded in the file `ci/zenodo.json5` and will be used in subsequent releases, subject to whatever updates we decide to make.

[Cranko]: https://pkgw.github.io/cranko/

**Comment by cjordan** [comment]
Sure, and thanks for offering!  My details:

Christopher H. Jordan
Curtin Institute of Radio Astronomy
0000-0002-1220-2940

**Comment by d3v-null** [comment]
Thanks Peter,

Dev Null
Curtin Institute of Radio Astronomy
0000-0003-2159-0911

**Comment by pkgw** [comment]
Thanks! I am not sure exactly what authorship policy we'd want to adopt if things ever really scale up here, but to start I'd plan to put myself first and then go alphabetically by family name, so we'd start with an author list of:

Williams, P. K. G.; Jordan, C. H.; Null, D.

If either of you would like to change that, let me know — either here or email to `pwilliams@cfa.harvard.edu` to discuss in a non-public setting.

**Comment by pkgw** [comment]
OK, I think we are ready to merge this and see if I wired up the new CI infrastructure correctly ...

**Pull request merged**
